# The URL the site will be built for

base_url = "https://wordius.com"

title = "Wordius"

author = "Jeff Porter"

description = "Most things Apple, with a leaning towards open source and free software"

# Compile all Sass files in the sass directory

compile_sass = false

# Feeds

generate_feed = true

feed_filename = "rss.xml"

# Taxonomies

taxonomies = [
    {name = "tags", paginate_by = 3, rss = true },
]

# Build a search index to be used later on by a JavaScript library
build_search_index = false

# ignored_content = ["*.{gif,jpg,png}"]

[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola

highlight_code = true

# highlight_theme = "css"

[extra]
# Put all your custom variables here

# The copyright notice

copyright = "{year}"
